# ===================================================================
# CONFIGURACIÓN GENERAL DEL MICROSERVICIO DE REPORTES
# ===================================================================
spring.application.name=ms-reportes
server.port=8086

# ===================================================================
# CONFIGURACIÓN DE EUREKA
# ===================================================================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# URLs de los microservicios de datos (via Eureka load balancer)
ms.preregistro.url=http://ms-preregistro
ms.validacion.url=http://ms-validacion
ms.operaciones.url=http://ms-operaciones
ms.fila.url=http://ms-fila-virtual

# ===================================================================
# CONFIGURACIÓN DE LOGS
# ===================================================================
logging.level.root=INFO
logging.level.com.frontintel.aduanas.ms_reportes=DEBUG
