# Nombre que identificará a este microservicio en la red
spring.application.name=eureka-server

# Puerto en el que correrá el servidor de descubrimiento (el estándar de Eureka)
server.port=8761

# Como este es el SERVIDOR, le decimos que NO se registre a sí mismo como cliente
eureka.client.register-with-eureka=false

# Le decimos que tampoco intente buscar otros servidores para sincronizarse
eureka.client.fetch-registry=false

# Desactiva el modo de autoprotección en desarrollo para limpiar rápido servicios caídos
eureka.server.enable-self-preservation=false