# Nombre que tendrá este microservicio en la red de aduanas
spring.application.name=ms-fila-virtual

# Puerto exclusivo para este servicio
server.port=8082

# Ruta para enlazarse de forma automática al Servidor Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/